"""The `crunchflow.output` subpackage provides tools for loading, parsing, and
analyzing output files generated by CrunchFlow and CrunchTope simulations.

It includes specialized classes for handling:
    - Spatial profiles of variables at different output times, with support for
      2D/3D gridded visualization (`SpatialProfile`)
    - Time series data extracted at specific cells in the model domain
      (`TimeSeries`)
    - Main output files containing speciation data for each geochemical condition
      (`MainOutputFile`, `Speciation`)

These modules enable users to extract numerical results, plot chemical
concentrations and spatial gradients, and integrate CrunchFlow output into custom
Python workflows for postprocessing, visualization, and model diagnostics.
"""

from .main_output import MainOutputFile, SpeciationBlockCollection
from .spatial import SpatialProfile
from .speciation import Speciation
from .timeseries import TimeSeries

__all__ = ["MainOutputFile", "SpeciationBlockCollection", "Speciation", "TimeSeries", "SpatialProfile"]
